### ISSUE TITLE
OSI approval?

### ISSUE THREAD

**Issue by ckaran** [deptofdefense/code.mil#10]
It would a good idea to try to get [OSI](https://opensource.org/) approval for any license you put forwards; this will make your code truly Open Source, which many outside projects require before they'll accept any code.  [ARL](http://www.arl.army.mil) has been trying to do so with its own license, but is awaiting more guidance from the folks at [code.gov](http://code.gov) before continuing the push.

**Comment by tomberek** [comment]
@ckaran : We are already pursuing OSI approval, thanks for the suggestion. We'll post here when we have more news.

**Comment by marctjones** [comment]
@ckaran Has ARL made the license they are proposing to OSI publicly available?

**Comment by BrandonBouier** [comment]
@ckaran we've been in conversations with the OSI, so they're aware of what we're doing.

**Comment by ckaran** [comment]
I apologize about getting on here late; I have been answering email traffic since I got in the office this morning regarding this issue, as well as others that have popped up due to the launch of [code.mil](http://code.mil).

@marctjones Yes, we put the license on the `license-discuss` mailing list at https://opensource.org/lists some time ago.  If you are on that list, you should see my updated message on there shortly; the message is **quite** long, but I'm hoping you'll take the time to read it through.

@tomberek @BrandonBouier I'd like to join forces with you; we should have as few agreements as possible, simply to reduce license proliferation.  If you aren't on the `license-discuss` mailing list, please get on there and take a look at the older discussions, as well as my recap that will be on there (I'd put the whole thing on here, but the issue would become a novella).
