### ISSUE TITLE
Is Code.mil just for select projects? Or can people build their own ideas?

### ISSUE THREAD

**Issue by ckib16** [deptofdefense/code.mil#100]
Hi all,

I've read the FAQ and Contributing. But I'm still a bit confused...

Is Code.mil for:
1. Anybody with an OSS idea they'd like to build for the DoD?
2. Just for collaborating on the specific projects that the Code.mil team is working on?
3. None of the above :)

I have some ideas I've always wanted to build for DoD use, but not sure that's the site's intent.

**Comment by shawoods** [comment]
@ckib16 That's a fair question! We will add something to the FAQ to make the "who" clearer.

1 - This is an interesting idea. We're super focused on getting ready to release our projects, but I will add this to the list of things to keep track of for future iterations.

2 - Collaborating on DoD projects being hosted by Code.mil is the main purpose of the site.

**Comment by ckib16** [comment]
@shawoods Ok great, thank you.

1. Understood. I do think there is a bunch of former military with dev skills who would be happy to make military tech a little better than what they had. Unfortunately no way to easily do that now as individuals.

2. Ok gotcha, makes sense. Thanks for the info and good luck.

**Comment by shawoods** [comment]
1 - That's awesome! We really want to collaborate with the retired military community on DoD open source projects. When we get closer to tackling how private developers might bring potentially helpful open source projects to DoD's attention, I'll reengage on this issue.

**Comment by Travis42** [comment]
How are those efforts coming along?

**Comment by jordangov** [comment]
Hey folks, I'm going to close this issue for inactivity. But you should stay tuned this week for updates on code.mil :)
