### ISSUE TITLE
NATIONAL EMINENT DOMAIN POWER & Who is Accountable? 

### ISSUE THREAD

**Issue by missyk5150** [deptofdefense/code.mil#108]
OUSD(AT&L) Acquisition Resources & Analysis (ARA)
Property and Equipment Policy
Accountability and Custody for 
Government Property and 
Contract Property

? eminant domain 
Does this include data property??

**Comment by missyk5150** [comment]
Publication of DoDI 5000.76 on Accountability of Internal Use Software

**Comment by BrandonBouier** [comment]
@missyk5150 I've never heard of an example of eminent domain being applied to open source software.

if you can provide such an example, I'll reopen this issue.

**Comment by missyk5150** [comment]
Okay maybe this article
https://www.google.com/url?sa=t&source=web&rct=j&url=http://www.cukier.com/writings/acumen-cukier-oct03.pdf&ved=0ahUKEwi8guuuvcrSAhUOyWMKHYnTDjY4ChAWCEIwBA&usg=AFQjCNF3tyooORcdXJyPsCm_ZqVHbsoNwg&sig2=KHdRXPmuN4xmeumcYGubng

**Comment by missyk5150** [comment]
Or this from the daily bell.com
- There have been no security breaches or embezzlements with bitcoin, only with 3rd party institutions holding bitcoins. Does Bernie Madoff invalidate the whole US dollar? Does a fraudulent gold smith operating a fractional reserve bullion bank invalidate gold?

"TOR facility that is supposed to keep bitcoin transactions anonymous was developed by the US military, of all groups"
- Doesn't matter who made it, it's open source.

Bitcoin is not gold. This article frames the conversation around a false paradigm, as if you can only own gold or bitcoin. They are two different things, and the reasons to own them are different.
3  
−
 Avatar
The Daily Bell  snax
a year ago
You seem a bit defensive about bitcoin. It does matter in our view that the US military created software that people use to enforce bitcoin anonymity. The security breaches and embezzlement seem to us to be a direct outcome of Bitcoin's organization and transactional needs. We have participated in numerous dialogues in which it soon became clear that counter-parties subscribed to the notion that gold is quaint and outdated. It is not. All that being said, we are happy that bitcoin proceeds and seems to be gaining traction. Anything that provides an alternative private money is a net positive in our view. We would tend to reject the perspective of one of its most important programmers that it is already a "failure."
