### ISSUE TITLE
Wait a minuite? Is this experiment unnecessary if this is really true??

### ISSUE THREAD

**Issue by missyk5150** [deptofdefense/code.mil#111]
http://www.thedailybell.com/editorials/anthony-wile-bitcoin-the-other-crash/
"TOR facility that is supposed to keep bitcoin transactions anonymous was developed by the US military, of all groups"
- Doesn't matter who made it, it's open source.

**Comment by BrandonBouier** [comment]
@missyk5150 I'm not seeing how the market value of bitcoin is in any way related to what we're doing with code.mil.
