### ISSUE TITLE
+1 for new direction of directly using a standard OSS license

### ISSUE THREAD

**Issue by gerv** [deptofdefense/code.mil#112]
This is a note of support for the new direction of directly utilizing an existing copyright-based open source license, and clarifying how this works via INTENT.md. Lots of us open source licensing geeks think this is clearly the right way to go, and applaud code.mil for its change of direction. Those who agree with this direction may want to comment here or star this issue.

Gerv

**Comment by pombredanne** [comment]
+1

**Comment by BrandonBouier** [comment]
@gerv @pombredanne Thanks to you both! Trust me when I say that we at DDS really appreciate it.

**Comment by richardfontana** [comment]
I agree, and I also like the way the DCO is used to address this issue. Actually I think this is the most impressive legal development in open source I've seen in years. :)

**Comment by tieguy** [comment]
As a former board member of the Open Source Initiative, drafter of the Mozilla Public License, and a variety of other roles in the open source legal community: +1. This is a very reasonable, constructive approach to a complex problem.

**Comment by BrandonBouier** [comment]
@richardfontana @tieguy Thanks a lot for the supportive comments!

I personally want to give a huge shoutout to my DDS coworkers @shawoods & @tomberek for their tireless effort to bring this to fruition!

**Comment by taz77** [comment]
Awesome effort! This is great to hear. After years of being a voice of open source and making small advancements on a micro level, it is great to see the DoD doing this as a whole. Not only will there be better code developed, but this will also expose development opportunities to more communities and help fuel the powerful force of competition!

**Comment by shaun-edwards** [comment]
+1, in my experience, anything outside a standard OSS license causes more pain than it's worth. Great progress!

**Comment by jordangov** [comment]
Thanks for the support folks. Closing the issue for a clean(er) issue backlog.
