### ISSUE TITLE
I favor the code.mil concept

### ISSUE THREAD

**Issue by doughodson** [deptofdefense/code.mil#116]
I work at the Air Force Institute of Technology (WPAFB) and maintain a project to support real-time simulation application development called "OpenEaagles."  This package is open, and posted on GitHub --
 yet it is clearly oriented at the military community.

I very much like the concept of code.mil, as it might simultaneously encourage more outside developers (with possibly much more experience and knowledge than intrinsic resources) to possibly participate in development and test processes -AND- serve as a bit of a focused marketplace for the DoD community.

GitHub is wonderful, but it can be daunting to find projects of particular interest that pertain to DoD type activities (which can often be highly technical in nature).

**Comment by BrandonBouier** [comment]
@doughodson we plan to expand the code.mil site beyond just pointing to this repo, to hopefully make it easier for you & others to find those DoD projects. We'll also be working closely with code.gov as well.

**Comment by carbtin** [comment]
@doughodson I'm a software developer with the Army and I do agree this is a great idea but I'm also trying to understand how the contribute process would work. Detailing project requirements could expose OPSEC issues and any proposal should be cleared at some level in DoD. Anything I work on could not be exposed in anyway.

**Comment by jordangov** [comment]
I'm going to close this issue for now. As @BrandonBouier pointed out, we are hoping to get a site up and running to act as that focal point (not GitHub). To @carbtin's points, I think it is off topic for this thread, but it is a good point. This is why each project will need to evaluate whether they fit in this model or not. And beyond that, how their contributions are handled. I think that discussion fits better into #117 though.
