### ISSUE TITLE
What is the legal basis for this agreement?

### ISSUE THREAD

**Issue by marctjones** [deptofdefense/code.mil#12]
Your agreement suggests that you are requiring everyone to include the terms of the agreement with the software when they make copies. Since all works of the federal government are in the public domain, can't anyone in the United States just copy the software without needing permission from this agreement, or following the terms of the agreement?

**Comment by shawoods** [comment]
This has come up a few times, but the idea that U.S. law requires Federal government employees to put creative works in the public domain is a bit of an overstatement. The U.S. Copyright Act does not explicitly define public domain. What the Act actually does is make works created by U.S. Federal government employees ineligible for copyright protections (17 U.S.C. 105). It’s an important distinction. Government works are still eligible for patents and trademark protections. 

Take a read on _ProCD, Inc. v. Zeidenberg, 86 F.3d 1447 (7th Cir. 1996)_, which cites to U.S. Supreme Court case, _Feist Publications, Inc., v. Rural Telephone Service Co., 499 U.S. 340 (1991)_.  There is some precedent in attaching agreements to public domain materials. It's also the basis for the NASA open source agreement.

The purpose of the agreement is not to create legal disputes that require DOJ enforcement, but rather to adopt the norms of the open source and free software communities by using widely adopted licenses.

**Comment by marctjones** [comment]
@shawoods Ahh I see;  you are intending to rely on a shrink-wrap agreement. Personally I think that case was wrongly decided, but then I am not a  circuit judge. But it is still good law. 

But I do not think a shrink-wrap case is not the best case to cite in this situation. Since the situation is more akin to a browser wrap agreement. Browser wrap agreements seem to receive less favorable treatment now. While I have mixed feelings about them click wrap agreements seem to far a little better. Both of these concepts seem to be children of ProCD. But I think the law has started to think a little bit more about the problem since then.

So while still important, I do not think ProCD is not the only case relevant to this discussion. For example you might want to check out [Nguyen v Barnes & Noble, Inc., 763 F.3d 1171 (9th Cir. 2014)](http://cdn.ca9.uscourts.gov/datastore/opinions/2014/08/18/12-56628.pdf). I will concede that I have not gone and pulled the law review article cited in footnote 2, but the foot note suggests it is on point to this discussion. 

I think considering the law in the United States is unsettled in this area, that it is premature to close this issue. I would also suggest that taking the position that hidden terms are acceptable is not in the spirit of the FOSS community. Despite Judge Easterbrook implied suggestion that all consumers are comfortable being bound by hidden contracts, I think the spirit of FOSS suggests sunlight is the better path.

**Comment by marctjones** [comment]
Or do I misunderstand. And your point is only that you can offer public domain works as consideration for a contract and you did not mean to rely on the concept of a shrink-wrap agreement.

If that is the case then I would agree. Nothing wrong with "charging a price" for providing someone with a copy of public domain material. But if you can bind anyone to a contract merely because you provide access to public domain material in some way without any limit, than I fear the day when a lawyer decides to take this to the limit by binding people to a contract when they read a magazine on the history of the civil war and then claims that readers of the magazine have agreed to pay the magazine publish a licensing fee any time they use public domain photographs of the civil war. Surely there must be a limit?

**Comment by shawoods** [comment]
@marctjones We are definitely not intending to charge a price or have hidden terms. Our hypothesis was that with some creativity we might be able to leverage contract law as a bridge to using existing open source license. Maybe it's not possible. Will reopen -- not intending to imply this is resolved. We are actively working a revision to the agreement based on all of this feedback, including yours.

**Comment by marctjones** [comment]
Sorry, I was not clear; By price I only mean that you are requiring an agreement to the contract as a price of using or copying or contributing. And by hidden terms I only reference another comment where one of your coworkers suggest that there is no reason for developers to even be aware of the agreement. In addition that that is how browser wrap agreements are often, and I think fairly, characterized since many people do over look them. 

I did not mean to imply you were doing anything nefarious. I take this to be an earnest good faith effort to explore possibilities. And I appreciate your department's eagerness to support FOSS. It does appear to be a novel legal strategy (which I think is a interesting idea as a legal geek); but obviously I think there might be cleaner and more practical ways to execute it.

You are correct that the NASA open source license does do something similar, but I think there is a reason why you do not typically see that approach in more commonly used licenses. Many FOSS licenses do mix in a contributor agreement, but it seems like the more modern approach is to have a contributor agreement as a separate document.

**Comment by BrandonBouier** [comment]
We've pivoted based on user feedback. Take a look at the current CONTRIBUTING.md

**Comment by fulldecent** [comment]
The updated CONTRIBUTING states that a license is to be chose by specific agencies. In this light, this instant issue is now out of scope for this project. I recommend to close this issue.

**Comment by tomberek** [comment]
@fulldecent The desire for an expressed legal basis is still valid even though it is now a CONTRIBUTING policy vice an agreement. 

@marctjones Most of this project assumes the license in question is compatible with open source or free software values. Is there a legal basis for the selection of a proprietary/non-free license as the only one under which the project owner will accept contributions? It does go somewhat against the spirit of this effort, but should it be an available option?

**Comment by marctjones** [comment]
@tomberek I do not think I understand your question. My point earlier about FOSS community values was that I believe the community values transparency. And I personally did not agree that the reasoning of the ProCD case supported transparency. Your newer approach avoids that particular criticism completely since it is not based on contract law to attach copyright like terms. 

I am personally think that contributor policies can to greater or lesser degrees reflect or reject FOSS community values, but not sure there is a restriction on what they can contain other then general principles of law and issues related to compatibility with the outbound license. 

It seems like your whole effort is trying to generalize away the licensing issues to simplify the contribution process while still being able to in essence select a license for the project despite the lack of government copyright. If that is your goal and you do it right then it seems like what license you select  should not be important, FOSS or proprietary.

In one sense the distinction between a proprietary license and a Foss license is only a matter of degree. Proprietary licenses generally give fewer rights to others than copyleft licenses, which give fewer rights than a permissive license. Besides the DCO explicitly speaking in terms of submitting the patch under a open source license, it doesn't seem the approach would require you to not permit a proprietary license. But I could be wrong. Not really sure if that addresses your question though?

**Comment by marctjones** [comment]
@shawoods I do not think I was giving your initial approach enough credit before. Not sure it changes my other concerns, but you are indeed right the public domain in a broad sense, and probably the best way to understand the concept, incorporates an almost complete lack of all forms of intellectual property protection. (Save maybe trade secret protect?) 

But I am not sure the strength of patents in pure software "inventions" is strong enough any more, after the impact of Alice v CLS Bank, to hang to too much on. And I typically think of the trademark protection in source code as pretty weak as well because trademarks seem to generally show up in there in the context of a nominative use. 

But to the extent that you can license those other IP rights besides copyright as consideration, it leaves the question of can you convert a copyright license into the terms/covenants of a contract. I suppose you could but it seems risky to do that blindly to an arbitrary license. It might lead to unpredictable results in litigation since most FOSS licenses were designed to operate by primarily granting a copyright license.

It also would limit the terms of the license to those in privity with the contract wouldn't it? Which I guess would require a little thinking about the downstream licensing impacts? Would a copyright license emerge eventually? Would or could it escape unlicensed without copyright protects, or could it escape unlicensed with copyright protection? If it never can escape does that mean we have some weird problem with the laws preference for alienability of property?

If a contract for sale/transfer could include some kind of perpetual-contract-based-quasi-copyright, doesn't that eviscerate the first sale doctrine as well?

Interesting idea though. Thanks for the thought exercise! 

I think your newer approach of focusing on the contributor agreement is probably legally more conservative so less risky, and has the virtue of being more familiar to the FOSS community. In light of the new approach I am going to close this issue, since my initial concern is no longer relevant to your current effort.
