### ISSUE TITLE
Different method to identify federal contributions

### ISSUE THREAD

**Issue by jdepriest** [deptofdefense/code.mil#121]
When considering contributions by federal employees as stated in section 3, it might be worth considering alternate approaches instead of the email address to allow a contribution to be tagged as a government contribution (no copyright protections). 

> If you are a U.S. Federal government employee and use a *.mil or *.gov email address, we interpret your Signed-off-by to mean that the contribution was created in whole or in part by you and that your contribution is not subject to copyright protections.

For example, an employee who works for an agency or group (ex: research group) that uses a *.com, *.org, or other address scheme may not even have a *.mil or *.gov address. Their contributions would not automatically be flagged appropriately. 

There may be other scenarios, but relying solely on an email address for attribution as a federal employee doesn't seem robust.

**Suggestion**:
Add another tag to the last lines of a commit to indicate a federal employee contribution (ex: [federal contribution])

**Comment by shawoods** [comment]
@jdepriest Sorry it took so long for us to respond! You make a valid point about the email addresses not providing a 100% capture rate. Thanks for making a specific suggestion to the problem! I anticipate we will experiment on resolving this issue in the next couple weeks with an upcoming project.
