### ISSUE TITLE
Outstanding issue closed with no comment

### ISSUE THREAD

**Issue by blakelapierre** [deptofdefense/code.mil#123]
Issue #14 was closed with no comment.

**Comment by paultag-gov** [comment]
this doesn't appear to be an issue, you can comment on the closed issue or reopen it.

**Comment by blakelapierre** [comment]
I think it's an issue that issues are closed with no comment. Is there no
issue handling protocol at code.mil, or are decisions made arbitrarily?

**Comment by paultag-gov** [comment]
I'm not particularly involved with code.mil -- code.mil is a part time project for some folks in a small (under 30 person) office at the moment with loads of other projects.

So, no. No protocol, no process, no paperwork, just empower good people to make decisions :).

Just treat this like any other free and open source community

**Comment by jordangov** [comment]
@blakelapierre You're right, issues should not be closed without comment. And I apologized for that in #14.
