### ISSUE TITLE
Clean up footer on mobile

### ISSUE THREAD

**Issue by jordangov** [deptofdefense/code.mil#139]
We should take a look at cleaning up the footer on mobile browser sizes. See the image below. The sizing of icons, spacing, and alignment should all be looked at and (probably) tweaked.

![code-mil-footer](https://user-images.githubusercontent.com/30059011/34778834-765410f4-f5ec-11e7-87fb-942d6e118084.png)

**Comment by arichiv-usds** [comment]
This is re-flowing reasonably
