### ISSUE TITLE
Improve contributing documentation

### ISSUE THREAD

**Issue by jordangov** [deptofdefense/code.mil#141]
We need to add information on how to run the site locally, build & test, what we need in a PR, etc.

**Comment by jordangov** [comment]
Added docs to `static-site` branch... @jgarber623-gov can you review?

**Comment by jgarber623-gov** [comment]
@jordangov Looks pretty good to me. A couple of suggestions:

1. A user shouldn't have to `gem install jekyll` since Jekyll is part of the `Gemfile`.
1. I would add a note about cloning the relevant branch (since the site's code isn't in `master`):

```sh
git clone -b static-site git@github.com:deptofdefense/code.mil
```

Otherwise, looks solid! 👍

**Comment by jordangov** [comment]
Ah, yes for 1 and 3... my mistake. On 2, we don't plan for this to be a different branch, it will be `master` sooooon. :)

Thanks!
