### ISSUE TITLE
Add proper "release" process

### ISSUE THREAD

**Issue by jordangov** [deptofdefense/code.mil#143]
This involves only deploying to a beta site on PR merge, but deploy to a prod site on an actual GH "release".

**Comment by fulldecent** [comment]
References:

https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A

https://stackoverflow.com/questions/24679889/how-to-start-travis-ci-deploy-only-when-tag-name-matches-a-regex

**Comment by arichiv-usds** [comment]
@jordangov all set on https://s3.amazonaws.com/beta.code.mil/index.html, LMK when the DNS is set and I'll close this out

**Comment by arichiv-usds** [comment]
Done!

**Comment by jordangov** [comment]
reopening to remind me to set DNS

**Comment by jordangov** [comment]
DNS change request sent.
