### ISSUE TITLE
Fix typo in how-to-open-source.md

### ISSUE THREAD

**Issue by sposhe** [deptofdefense/code.mil#162]
`code.mil/_pages/how-to-open-source.md`, line 20: "opening sourcing" --> "open sourcing"

"This is one suggested workflow for opening sourcing an existing project"
should read
"This is one suggested workflow for open sourcing an existing project"

**Comment by jordangov** [comment]
Thanks! We'll try to get to that soon. (But feel free to submit a PR if you're interested!)

**Comment by sposhe** [comment]
Thanks. I started to do a PR but then read through the contribution guidelines. Would I have to follow the DCO process for something this small?

**Comment by jordangov** [comment]
Yes, we would still need that. However, we use a "DCO light" sort of process, so all you need to do is add your name and email to the "CONTRIBUTORS.md" file along with the PR. :)
