### ISSUE TITLE
I always feel happy contributing to MIT licensed projects.

### ISSUE THREAD

**Issue by nanjizal** [deptofdefense/code.mil#19]
I don't know or care about the limitations that you may have on licences since I am not from the US. 

But I think the modern approach is to use MIT licences where ever possible on all github projects, then users can use the code fairly freely for commercial, experimental or educational use. 
If you have a problem creating the MIT licences directly then perhaps hire a company who can, then contribute to the code, if your not allowed to contribute then you probably should try to change your laws.  

Simple MIT licences will mean that any useful code can attract quality coders that are willing to contribute, I think Apache2 and BSD3 are pretty common.  I get a bit sad with code that has patents or GPL licences, although ported some recently as I can't use it easily on anything commercial.

If you start making up new licenses it only become confusing and developers from the wider world will just pass on making contributions.

Even with a MIT license you will find many people don't even have the time to try or make use of your code let alone contribute, so to use more restrictive opensource ones or adding special conditions will just mean your less likely to get contributions.  

For instance Facebook opensources code like 'React' that is very popular but they put additional clauses which mean a project they have that recently interested me, when I saw the clause I stopped looking at the code, if work requires me to use the library then I would, but would try to avoid making contributions.

To me a MIT license means that I can use the code pretty freely and so if it's any good and I can contribute something then it's worth my time.

Sorry if my comments are not relevant but trying to give perspective of opensource external possible user.

**Comment by tomberek** [comment]
Thank you for the perspective. We've had these same discussions internally. We did not want to endorse a particular license and we intend each project to decide which license is appropriate for them. Some may choose MIT, BSD, Apache, or eventually GPL. We did not want to take that choice away from them. 

Closing this issue, feel free to re-open to comment or continue the conversation. 

To clarify: this agreement is a thin wrapper around a license (chosen by the project), so it re-uses the existing licenses everyone is familiar with.
