### ISSUE TITLE
Section 6 could be header plus paragraph 

### ISSUE THREAD

**Issue by dosaygo-coder-0** [deptofdefense/code.mil#22]
The section 6 header is hard to write, but maybe something like, Rights Covering this Agreement

And the current header could be its paragraph.

I think it currently looks like section 6 is more important than the rest because it is all header.

**Comment by BrandonBouier** [comment]
@dosaygo-coder-0 Thanks - would it be possible for you to submit a pull request showing how you think it should look?

**Comment by tomberek** [comment]
Closed as addressed by PRs. Thanks for the suggestion.
