### ISSUE TITLE
Why not CC0?

### ISSUE THREAD

**Issue by Xe** [deptofdefense/code.mil#24]
https://creativecommons.org/publicdomain/zero/1.0/

This is a public domain license that might help for this.

**Comment by shawoods** [comment]
Check out the third question in https://github.com/deptofdefense/code.mil/blob/master/FAQ.md.

**Comment by tomberek** [comment]
Closing issue as answered. Please re-open if needed.

**Comment by stuarthannig** [comment]
Direct link: https://github.com/deptofdefense/code.mil/blob/master/FAQ.md#since-software-created-by-us-federal-government-employees-does-not-have-copyright-protections-in-the-us-why-not-just-put-it-in-the-public-domain-and-use-cc0-10-for-international-jurisdictions-where-you-have-copyright
