### ISSUE TITLE
Immediate, Crowdsourced Data from Disaster Areas

### ISSUE THREAD

**Issue by MadArkitekt** [deptofdefense/code.mil#29]
My proposal will collect crucial pictorial, cartographic and topological data during the early stages of disasters, natural or otherwise. 

Among witnesses and first responders, smartphones abound. During disasters or emergency responses, information, specifically environmental, reigns king. 

Say an earthquake brings a building down. First responders haven't a much data regarding the area around the building, how it fell, what pther structures' integrity has been compromised, etc. 

What if the people already on scene had received a notification similar to an AMBER alert, were asked to download a free app, open said app, and hold up their phones. 

Utilizing a mixture of sonar, GPS, geofencing, and computer vision the crowd could help paint a picture of the landscape, and the app also allows for further communication with the crowd, advising those in hazardous areas to relocate. 

Im typing this from a phone after studying your newly published repo, please excuse the brevity. I will expound upon my idea later today. 

- The MadArkitekt

**Comment by BrandonBouier** [comment]
@MadArkitekt this repo is to solicit feedback for our draft Defense Open Source Agreement. While I appreciate your enthusiasm for your proposal, it should not be filed as an issue under this repo since it is not applicable. So I'm going to close this comment.

**Comment by MadArkitekt** [comment]
Sorry about that, Github client on phone harder to navigate.
