### ISSUE TITLE
Happened across Code.mil

### ISSUE THREAD

**Issue by grant51802** [deptofdefense/code.mil#31]
Maybe i should have put this under projects?

I'm new to all this coding. I started because I'm trying to develop a program that can track training events and the vast amounts of data that happen just in a single training event. Both active and reserve components consume resources, train personnel, absorb training land, etc... Those are the easy numbers to follow.  More over, I wanted to create a database that can track evaluations, Objective T ratings, critical and leader tasks executed within CATS tasks, and other variables that I've drawn up but need to create.

**Comment by BrandonBouier** [comment]
Hi @grant51802.

This repo is to solicit feedback for our draft Defense Open Source Agreement. Unless I'm mistaken, what you're talking about doesn't seem relevant to that. Care to elaborate?

**Comment by grant51802** [comment]
It's probably not relevant. To be honest I'm fumbling around trying to learn coding to do some of the things I mentioned earlier. I ended up stumbling onto your page here where I think I just saw Open Source and DOD. I figured it can't hurt to post something.

Maybe you can help steer me in the right direction though. 

I am currently doing AC/RC (not sure how familiar you are with specific branch positions). Simply put, I evaluate units as they train based on out task lists. I've noticed that there might possibly be no accountability with resources used during training (that I can tell), and there is no posterity with the evaluations we do. 

We go out to training events, evaluate the unit, compile after action reviews and give them to the units. Past that...nothing gets saved, compiled and studied. Just saying to a commander that a unit is doing good sates everything but why? Saying a unit isn't that good raises every red flag in the book and we have to explain in detail why. I wanted to bolster that argument with concrete data that I can show trends and statistics with.

I'm thinking, if I can not only show quantifiable performance based on our pre-established standards, but trends over the years and between command teams, it would give higher echelons a better view into what is going on at lower levels increasing the accountability and quality of units and leaders.

The tangible data I want to capture includes:

Fuel, PLL, ammo, etc.. both resourced and consumed
Personnel present for training: leaders (NCOs and Officers by position) and Soldiers
Equipment on hand for training that works and that doesn't work
Hours spent actually training vs sustaining

The more intangible data includes:

Tasks performed
Evaluations of those tasks
By Unit, after action review comments compiled into a database
Observer/ Controller's raw assessments of units
Larger exercise summary database. 

I've scribbled many pages working this idea out. Now I'm trying to learn how to tell a computer to do what I want it to do. Any help or direction you have would be greatly appreciated!

**Comment by storrgie** [comment]
@grant51802 might want to see if there is a security classification guide for the payload of the data you're trying to use during this simulation. It's likely _not_ the best idea to throw out details of what you're working on until projects like [ARL Open Campus](https://www.arl.army.mil/opencampus/) or this repository figure out what sort of standard pathway a developer can take to bring an idea from the **inside** to the **outside**.

Nobody is going to bite and discuss your project details here.

**Comment by tomberek** [comment]
@grant51802 It seems like your project would be well suited to be open source and perhaps a good use of our Defense Open Source Agreement. The program would not be classified as long as you don't publish real data or results from training events. This would allow other units to also use it and perhaps improve upon it.

Closing this issue as responded to.
