### ISSUE TITLE
seems like doing a DOD variant of bsd-2 or mit license might make it simpler

### ISSUE THREAD

**Issue by cartazio** [deptofdefense/code.mil#35]
https://opensource.org/licenses/MIT
and https://opensource.org/licenses/BSD-2-Clause being stable urls for reference

specifically: it seems that the license only really talks about the initial code release by government employees, and doesn't clearly layout what rights (and/or contractual agreements) are granted by contributions that aren't by government employees.

the current language doesn't read like a clear decision tree of whats going on. 

the MIT and BSD2 licences are a bit more straigh forward in language, the only extra complexity  lies in contributions / the initial project that are authored by government employees. 

Also i'm unsure if the language of this contract had any editorial feedback from a lawyer with intellectual property experience. It punts handling contributions by 3rd parties to the developer certificate of origin, but does not itself talk about granting those rights forward

**Comment by tomberek** [comment]
@cartazio : You are correct, this is mostly a mechanism for the initial release by the government, after that, the DCO and the per-project LICENSE.md governs contributions by non-government contributors.

We have an alternate (perhaps simpler) proposal which we'd love comments on (see #33,#34)

Closing as answered. Feel free to re-open to continue.
