### ISSUE TITLE
BSD or D&R License

### ISSUE THREAD

**Issue by rthbound** [deptofdefense/code.mil#40]
First, welcome to the open source community.

Now onto business. I'd like to urge the DoD team here to consider adopting a license similar to [this BSD or D&R](https://raw.githubusercontent.com/indeyets/syck/master/COPYING) license.

I'd prefer something like "GPL or D&R", but it's definitely the "or D&R" part that's most important to me.

I look forward to seeing what comes of this endeavor! 🙈 🎉

**Comment by techiousnerdious** [comment]
Sorry about my ignorance on this subject but I am new to github and to coding outside of college.  Can you guys explain why their current license is not sufficient? I am excited to start contributing code, but I am unsure about all the license issues people are haveing when the project is open source anyway.  Looking to learn something new>

**Comment by rthbound** [comment]
@techiousnerdious I'll discuss your question a little, but first want to say that this ticket is a little tongue-in-cheek in that the D&R license is a joke. Read the second part of the link in my issue for a chuckle.

Open Source licenses ranges in permissiveness.  [Here's a comparison chart](https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses#General_comparison).

I've always been fond of the MIT License, which is extremely permissive -- maybe too permissive for government works (debatable). I particularly like the **GNU General Public License** because:

[> GNU General Public License is intended to guarantee your freedom to
share and change all versions of a program--to make sure it remains free
software for all its users.](http://www.datamation.com/open-source/open-source-debate-copyleft-vs.-permissive-licenses.html)

To quote the GNU GPL itself:

>   When we speak of free software, we are referring to freedom, not
> price.  Our General Public Licenses are designed to make sure that you
> have the freedom to distribute copies of free software (and charge for
> them if you wish), that you receive source code or can get it if you
> want it, that you can change the software or use pieces of it in new
> free programs, and that you know you can do these things.
> 
>   To protect your rights, we need to prevent others from denying you
> these rights or asking you to surrender the rights.  Therefore, you have
> certain responsibilities if you distribute copies of the software, or if
> you modify it: responsibilities to respect the freedom of others.
> 
>   For example, if you distribute copies of such a program, whether
> gratis or for a fee, you must pass on to the recipients the same
> freedoms that you received.  You must make sure that they, too, receive
> or can get the source code.  And you must show them these terms so they
> know their rights.

**Comment by shawoods** [comment]
@rthbound Adopt BSD how? Federal government employees don't have copyright. Are you just commenting on the pros and cons of different permissive licenses generally or do you have a comment about the mechanics of how Federal government employees can use open source licenses even without copyright?

**Comment by tomberek** [comment]
@rthbound We even looked at http://www.wtfpl.net/ for a bit!

Thanks! We're looking at a revamp (#33,#34) and would appreciate your comments.

**Comment by rthbound** [comment]
@shawoods, #40 is doing two things:

- celebrating the [DOD](https://github.com/deptofdefense)'s arrival to the open source community.
- proposing a novelty license in jest, for fun.

My subsequent comment is in response to @techiousnerdious, who stated unsureness:

> about all the license issues people are having when the project is open source anyway

and that he is:

> Looking to learn something new

**Comment by rthbound** [comment]
@tomberek, #33 and #34 have you on the right track. The concerns raised in #33 are spot on, and I think #34 is describing a good way forward. The question that remains, I guess, is "what is that License XYZ"?

@konklone's comments [here](https://github.com/deptofdefense/code.mil/issues/34#issuecomment-282491289) are spot on. Don't let it get too hairy, folks lawyers won't let them use anything.

@eshellman is right on [here](https://github.com/deptofdefense/code.mil/issues/33#issue-210187283). As much as possible, Keep it Stupid Simple.

What @konklone is talking about seems very similar to what they're doing over in https://github.com/unitedstates/images.

**Comment by tomberek** [comment]
@rthbound Ideally, XYZ is whatever each project's manager chooses as appropriate for them. Some may choose GPL to encourage the project remaining open. Some may like MIT to encourage contribution. Some may choose a CRADA-style research license to ensure the government can use derivatives. There are so many possibilities and situations that I'd prefer not to pick, only to provide a framework where projects run into fewer bureaucratic hurdles as they try to release.

**Comment by rthbound** [comment]
@tomberek I will take that to mean the [Death and Repudiation (D&R) License](https://github.com/indeyets/syck/blob/master/COPYING#L26-L53) is on the table and available for use when appropriate. I _think_ this resolves my concerns, thank you so much.

Closing. :octocat:
