### ISSUE TITLE
Refactor/cleanup repository

### ISSUE THREAD

**Issue by enckse** [deptofdefense/code.mil#42]
I would offer a merge myself but since I don't control code.mil (though it is "representing me" as a member of the DoD community...), this repository, or the web presence you've opted to go out with:

* Please explain what each file is in the README. Initially seeing LICENSE.md and LICENSE-agreement.md is confusing. As is CONTRIBUTING.md which (from reading it) doesn't apply here (I believe). FAQ.md should probably be part of README.

* Refactor so that index.html and CNAME (if required) are not in master branch. If both of those files are actually necessary to redirect http://code.mil (since #6 remains open sadly) they should be moved to a branch or hosted in another fashion and not in the same repo and branch as the place where collaboration about licensing is expected.

For the sake of people visiting and you trying to get input, please take a pass at these things.

**Comment by storrgie** [comment]
Please place the artifacts that you seek contributions on in a sub-folder so as to reduce confusion about accepted contributions. See #8.

**Comment by nschonni** [comment]
Proposed partial cleanup with #63. Creating a "gh-pages" branch and moving the index.html and CNAME would have to be done by a project maintainer

**Comment by tomberek** [comment]
@nschonni @storrgie Accepted #63 and created gh-pages. Closing as complete.
