### ISSUE TITLE
Room for another?

### ISSUE THREAD

**Issue by th3j35t3r** [deptofdefense/code.mil#47]
I'd like to get involved with this initiative. Just point to where you need me.

**Comment by missyk5150** [comment]
In my opinion until the experiment is finalized only E.G.G. HEADS THAT can answer the DOD with some advanced level of technical word usage, able to show the DOD ability to go beyond just "getting what the idea is" and more like what the idea can really become beyond  the given requirement that they are experienced or qualified,.... The government wants a person they would say is essential to helping advancement. The government may see the person as rare and valuable to them, Yet in reality the truth is where they can find one,,, these days they can find 7 more to replace that one with.. If you are able to qualify for the final solution of the DRAFT here and not become a statistic for TERMINATION..... Go to the closest site for hiring jobs that are with the U.S.  require a Q-Clearance w/o restriction NSA/CIA background check that can be passed if you are considered for employing... What really is the answer once qualifications are passed.. ????  I feel its alway been rule #1 whats in it for them?? The news can incorporate a lot of theories on current threats like big time in hacking the security of and thus exposing a weakness in any major programs coding... my guess is really just up in the clouds...    CLOUD TALK IS JUST B.S. ALMOST AS MUCH AS PIPE DREAMS... just puffed up ideas just sharing wishes dreams and hopes.


PSY-OP ADVANTAGE 
Of political propaganda in media and other social  activities to subliminally steer masses of individuals to a certain idea to get a desired outcome to have a vantage in the situation and the upper hand to be the one that ultimately will have and keep the US best IN controll and the Victor.

**Comment by missyk5150** [comment]
#47

**Comment by missyk5150** [comment]
I should have opened my own issue before I commented here if I offended you I apologise... I am learning and details like signing off  were not known to be until just now...

Signed-off-by: Missy Krisik <missyk5150@gmail.com>

**Comment by tomberek** [comment]
Closing as off-topic.
