### ISSUE TITLE
One of the Federal issues I found in the open source world that may give more reason to the experiment.

### ISSUE THREAD

**Issue by missyk5150** [deptofdefense/code.mil#53]
I did not create this i just copied and pasted it from the site here at : whitehouse.gov http://www.whitehouse.gov/copyright

Case Studies/Whitehouse.gov

http://wiki.creativecommons.org/images/1/1f/Us-whitehouse-logo.jpg
whitehouse.gov http://www.whitehouse.gov/copyright
.

Evaluation Information.pngReview
Page Importance:	
Page Quality:	
Discuss this evaluation
www.whitehouse.gov is the official website of United States’ President Barack Obama and his Administration.
Our commitment to openness means more than simply informing the American people how decisions are made. It means recognizing that government does not have all the answers, and that public officials need to draw on what citizens know. — President Barak Obama, 1/21/09, http://www.whitehouse.gov/ope/

Overview

The United States of America’s President Barack Obama was sworn in on the 20th of January 2009 after being elected on the 4th of November 2008 to be the 44th leader of the American people. During the period between election and inauguration, the President elect’s transitional website (www.change.gov) was licensed under a Creative Commons Attribution 3.0 Licence.[1] This meant that all content posted by the President elect, his team and any contributors was subject to this licence. During his inauguration, at 12:01pm on the 20th of January 2009, President Barack Obama launched the whitehouse.gov website, the official website of the Obama-Biden Administration also incorporating the same Creative Commons licence (see below).[2]

Visitors to whitehouse.gov can choose to view information from a variety of categories, these being:

“The Briefing Room” which includes the White House Blog, weekly addresses, slideshows, speeches and official statements from the Obama-Biden Administration;
“The Agenda” which lists the “Obama-Biden Administration’s positions on everything from healthcare and the economy to alternative energy and foreign policy”;
“The Administration”, which as the name suggests, provides information about the various key figures in the current Administration;
“About the White House” which provides a historical overview of the US Government; and
“Our Government” which discusses democracy in the form of the various branches of government.
Of the above, perhaps one of the most interesting aspects of the site is the White House blog. The White House blog discusses various events from spring gardening with the First Lady to live blogs of the Vice President’s meeting of the Middle Class Task Force for green jobs. The White House blog is the US Government’s tool to keeping the American people in-step with the most recent developments in politics, and is pitched on the site as offering exactly that - the “Latest News & Updates”.

After visiting the site, it is easy to observe that the US Government’s goal in maintaining whitehouse.gov is to appear connected with its people. This is apparent from the weekly addresses, slideshows and constant blogging, which aim to create a sense of unity and inclusion for the American community. In teaming with this theme, the Office of Public Liaisons which can be accessed from the website’s Administration tab, offers an opportunity for the American people to give the Obama-Biden Administration feedback and suggestions on running the country. The idea behind this is obvious – “to take the Administration out of Washington and into communities across America, stimulating honest dialogue and ensuring that America's citizens and their elected officials have a government that works effectively for them and with them.” This initiative works in accordance with the idea of using the Creative Commons licence, and building a democracy based on true public participation, and will be discussed in detail below.

Statistics

In March 2009, average weekly traffic rankings for whitehouse.gov were 3,080 people which had increased by an average of 2,729 people per week, for three months. From these users, 72.5% came from the United States of America.

Licence Usage

Pursuant to the United States of America Code, Title 17, s 105, “copyright protection…is not available for any work of the United States Government, but the United States Government is not precluded from receiving and holding copyrights transferred to it by assignment, bequest, or otherwise.” As a result, the information posted by any of the Obama-Biden Administration on the whitehouse.gov site is not capable of being protected by copyright law.

However, this rule does not apply to third party content posted to on whitehouse.gov. Therefore, to align with the open principles of the website, people posting material to the site are required to license that material under Creative Commons Attribution 3.0 licence. The White House copyright policy states that as a result “visitors to this website agree to grant a non-exclusive, irrevocable, royalty-free license to the rest of the world for their submissions to whitehouse.gov.”[3] This licence enables visitors to the site to copy, distribute, display or perform any of the text or images contained in the site, as well as to make derivative works of these. The only condition to such use is that visitors must attribute the work remixed, copied, distributed, displayed or performed to the author but not in such a way as to imply that the author has endorsed the derivative work.

This licence is the widest Creative Commons licence available that doesn’t give away all rights of the author. There are no restrictions with respect to using any material in a commercial manner, neither are there any restrictions about share-alike conditions. The use of this licence reflects the prohibition that copyright protection (of any kind) is not afforded to the United States Government or its products. In the event that a more onerous Creative Commons licence was imposed on Third Party content, this may be argued as being out of line with this principle.

Motivations

Creative Commons licensing enables the Obama-Biden Administration to work collaboratively with the American people, and demonstrates a genuine focus on democratic participation in the running of the country. The ability to take information from the site with only an obligation to attribute it to the author means that visitors to the site can be fully informed and in turn can fully inform others. Additionally, this process means that the circulation of inaccurate material is kept to a minimum because of the openness of the collaboration process.

Furthermore, after receiving a great response from using a Creative Commons licence on his change.gov site (even though the content contained was copyrightable at the time given that it was not US governmental material yet), President Obama’s choice to continue with the Creative Commons license for whitehouse.gov was strategically logical. Choosing to use the Creative Commons licence clearly influenced and reached out to those sectors of the community who were in tune with current creative technological advancements, and whose attention may not have been attracted otherwise. Creative Commons blogger, Fred Benenson encouraged the use of Creative Commons by President Obama, as did others with comments like “Thank you again, Mr President,” and “How awesome” posted on blogs all over the internet. The clearly favourable responses from the American people to the use of a Creative Commons licence on whitehouse.gov, indicates that the President’s team was successful in utilizing the licence to create a truly democratic process in a creative online environment. The political results of this move are a clear motivation for the use of the Creative Commons licence.

Finally, the convenience of the archiving process of the website has been made abundantly simpler given the use of the Creative Commons Licence. As one blogger put it, using a CC licence for 3rd party material on whitehouse.gov “would make the archiving of the website a much easier proposition.” Obviously the ability to forego any copyright processes and other such records would be a motivation for the maintainers of whitehouse.gov given that the site will encourage high traffic and be in use for the entire term of President Obama.

It can be gathered from comments by the administration on the site, and in particular those on the site of the Office of Public Liaison, that the current US Government is legitimately interested in generating public interest around policy issues in order to build a greater democracy.

Technical Details

Whitehouse.gov has implemented the license image and linked to the Creative Commons Attribution 3.0 United States deed. The license can be found on the Copyright Policy page:

Whitehouse1.png

Whitehouse.gov has not implemented any of the CC REL license metadata specification. The code below generates the license mark above:

<p><a href="http://creativecommons.org/licenses/by/3.0/us/"><img src="http://i.creativecommons.org/l/by/3.0/us/88x31.png" alt="Creative Commons License" /></a></p> <p>Except where otherwise noted, third-party content on this site is licensed under a <a href="http://creativecommons.org/licenses/by/3.0/us/">Creative Commons Attribution 3.0 License</a>. Visitors to this website agree to grant a non-exclusive, irrevocable, royalty-free license to the rest of the world for their submissions to <a href="http://www.whitehouse.gov/">Whitehouse.gov</a> under the <a href="http://creativecommons.org/licenses/by/3.0/us/">Creative Commons Attribution 3.0 License</a>.</p>

References

Jump up ↑ The Office of the President Elect, Copyright Notice (2008) at 19 March 2009.
Jump up ↑ Benenson, F Whitehouse.gov’s 3rd Party Content Under CC-BY (2009) Creative Commons, at 20 March 2009.
Jump up ↑ The White House, Copyright Notice (2009) at 20 March 2009.
Categories: CasestudyUSAPublic domainOpensource
This wiki is licensed to the public under a Creative Commons Attribution 4.0 license.
Your use of this wiki is governed by the Terms of Use.
Privacy policy
About Creative Commons
Disclaimers
This page was last modified on 13 October 2012, at 17:44.
Theme based on bootstrap-mediawiki by BorkWeb.

Creative Commons Attribution 4.0 Powered by MediaWiki

-s
Signed-off-by: missy krisik <missyk5150@gmail.com>

**Comment by missyk5150** [comment]
I am putting the effort to show a cc licence on the material i am submitting here because I myself took my time to create this comment. "This comment"
Signed-off-by:<Missy Krisik><a rel="license" href="http://creativecommons.org/licenses/by/3.0/us/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/3.0/us/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/3.0/us/">Creative Commons Attribution 3.0 United States License</a>.

**Comment by missyk5150** [comment]
Signed-off-by: missy krisik <missyk5150@gmail.com>

**Comment by missyk5150** [comment]
I feel the new president is who needs to be considered the one we need to protect here.. so if the obama admin made the whitehouse.gov site so admired. But the liberal hacks wanting tax forms and other personal sensitive documents about the current presidential family were not a real concerning threat at that time....who knows what the dod wants i am done wracking my mind over and over it.
Signed-off-by: Missy Krisik <missyk5150@gmail.com>

**Comment by tomberek** [comment]
Thanks for the comment. Please see [the FAQ](/FAQ.md) for the response for CC and what this project's intentions are.

**Comment by missyk5150** [comment]
TYSVM.  :-)
