### ISSUE TITLE
consider using Mercurial as well as git

### ISSUE THREAD

**Issue by markgalassi** [deptofdefense/code.mil#54]
Please make sure that people can create Mercurial repositories as well as Git ones.  I can elaborate on the reasons for it if you want.

**Comment by impredicative** [comment]
Please do elaborate why because people including myself are sorely lacking education on the reasons why Mercurial matters.

**Comment by markgalassi** [comment]
Ouroboros> Please do elaborate why because people including 
    myself
    Ouroboros> are sorely lacking education on the reasons why 
    Mercurial
    Ouroboros> matters.

Mercurial and git are isomorphic in almost all important aspects 
of
distributed version control.

Apart from the technical differenes, which are discussed in many
articles but which are ultimately small differences, the main 
issue is
the type of workflow and the ease of understanding for someone who 
does
not use it regularly.

Mercurial can be used effectively by people who don't commit many
times/day, and one of its models of workflow looks a lot like the 
way
cvs/svn should have been.

People get used to git but most people who use it use use it 
poorly and
with risk.  This xkcd explains it well:

https://xkcd.com/1597/

My specific situation: I am an astrophysicist and work with 
physicists
(I'm in Los Alamos), some of whom are quite sophisticated and 
would be
able to "get" git; others would use it very poorly and avoid doing
proper branching just because of their emphasis.  They write a lot 
of
code, but will not wrap their heads around git properly.

So I think it would be good to start from the ground up doing what
savannah and bitbucket do: allowing both mercurial and git repos.

**Comment by tomberek** [comment]
@markgalassi Until we have a more robust/proper/official path forward, you may use:
https://bitbucket.org/tomberek/code.mil-hg

**Comment by tomberek** [comment]
Closing as resolved. Marking with backlog to pursue a more long-term solution in the future.

**Comment by enckse** [comment]
I don't believe that starting a project on bitbucket was the correct solution...if I go and open an issue there what's going to happen? It's going to fragment discussion (brb)
