### ISSUE TITLE
please try to adhere to the GNU ethical repository criteria

### ISSUE THREAD

**Issue by markgalassi** [deptofdefense/code.mil#55]
I would be great if your web site could be used with 100% free software.  This means, for example, not mandating the use of proprietary javascript to create one's account.

The full GNU guidelines are here:

[https://www.gnu.org/software/repo-criteria.en.html](https://www.gnu.org/software/repo-criteria.en.html)

**Comment by tomberek** [comment]
For now we are using GitHub. What alternative would you recommend which is GNU-friendly?

**Comment by flemingtech** [comment]
Markgalassi,

If your web browser and JavaScript clone doesn't work with open and standardized ES5 code, how is that anyone's problem but yours?

**Comment by BrandonBouier** [comment]
We've pivoted based on user feedback. Take a look at the current CONTRIBUTING.md

**Comment by fulldecent** [comment]
This issue is not relevant for the new project as based in the new CONTRIBUTING guidelines. I recommend to close this issue.

**Comment by BrandonBouier** [comment]
I agree.
