### ISSUE TITLE
WTFpl would work well.

### ISSUE THREAD

**Issue by MorrisR2** [deptofdefense/code.mil#56]
A license similar to the WTFpl would satisfy the expectations that all code should have a license, while not putting any restrictions on the use of the code.  It's essentially a disclaimer of copy rights, written in the form of a one-sentence license.

**Comment by MorrisR2** [comment]
Due to issues with the precise wording of the WTFpl, I hereby propose the Morris Public License:


Morris Public License Version 1.0

1) Authorization to copy, modify, and distribute

Any person, may copy, modify, distribute, or otherwise use the work in any form, without copyright restriction of any kind. All copy rights are hereby disclaimed.

2) Disclamer of warranties
THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW. EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM “AS IS” WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

**Comment by tomberek** [comment]
Closing as duplicate to #52. Assiging @shawoods to take a look at the language.
