### ISSUE TITLE
Minimally Adapt an Existing License

### ISSUE THREAD

**Issue by LawyerMe** [deptofdefense/code.mil#57]
May I suggest you use an existing license with the minimal necessary modifications rather than re-inventing the wheel?

Depending on what other stakeholders and adopters you are trying to get on-board you may choose one of several existing licenses. Then make changes that are as compact as possible and offset them from the rest of the license to the extent possible. While I am not suggesting it is the best license for this purpose, consider how you might adopt the BSD license. Simpler is better if you want developers to be comfortable with it. For example:

<hr/>

**To the extent this work is entitled to Copyright protection, this work is** Copyright (c) YEAR, HOLDER.  All rights reserved **except as permitted below**.

**Regardless of whether and to what extent this work is entitled to Copyright protection, the contractual right to use this work to the extent permitted below is granted to all persons provided the described conditions are met. These rights are granted in consideration of the benefits to the author of membership in and contribution to the open source community, including such benefits as may arise from study and adoption of the author's contributions.**

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the <organization> nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

**Comment by SamuelSchlesinger** [comment]
Having the legal precedent there with the license is really comforting, particularly when using something of the US governments, no? I'd advocate for using an existing license exactly as is, as do most entities that publish their code open source.

**Comment by SamuelSchlesinger** [comment]
Wait no I think I at least misunderstood, the LICENSE-agreement is not the same as LICENSE, and the LICENSE will be changed to suit the individual project.

**Comment by tomberek** [comment]
@SamuelSchlesinger That is correct. This proposal tries to serve as a way to get to a standard well known license in spite of the lack of copyright for federal employee work products, while still allowing project managers to choose what is most appropriate for them.

Our goal is to not introduce yet another license into the ecosystem (proliferation). Creating a new license is a valid endeavor, but that would be a distinct effort from this one.

Closing issue as answered.
