### ISSUE TITLE
Contract locks out under-18 contributors?

### ISSUE THREAD

**Issue by dylmye** [deptofdefense/code.mil#58]
Hi, sorry if I'm mistaken but in most countries one needs to be over the age of majority to complete a contract?

From [USLegal](https://contracts.uslegal.com/contract-by-a-minor/):
> With some exceptions, a contract made by a minor is voidable.

From [Net Lawman UK](http://www.netlawman.co.uk/ia/entering-contract-minor):
> Further, a contract with a minor is voidable. That means he or she is able to cancel any contract at any time before reaching the age of 18 and for a reasonable period after that time. There is no requirement for him or her to have a justifiable reason for this, it can be done on a whim or where it may be advantageous to the child to do so.

Would this mean that those not in the age of majority in their country, or those unable to sign a contract in their country or the United States, would be unable to legally contribute without their parent signing for them?

Thanks!

**Comment by BrandonBouier** [comment]
We've pivoted based on user feedback. Take a look at the current CONTRIBUTING.md

**Comment by shawoods** [comment]
@dylmye Even though we've updated the strategy to drop the use of contract law, I did want to say that your comment was super on point.

**Comment by tomberek** [comment]
The new DCO-based approach seems to sidestep this issue. @dylmye At the very least, the new approach is no worse than existing licenses/practices.

**Comment by marctjones** [comment]
@tomberek I would also recommend closing this issue as beyond the scope of this project. It is true that "infants" and minors have a limited ability to consent to contracts. And similarly they have a limited ability to grant licenses, but this is a general limitation contained in most legal regimes. By its nature this legal limitation on infants can not generally be modified and is not really specific to this licensing strategy.

**Comment by tomberek** [comment]
Agreed.
