### ISSUE TITLE
DoD & gov workers - let's discuss at 3pm ET today

### ISSUE THREAD

**Issue by BrandonBouier** [deptofdefense/code.mil#64]
There has been a good discussion about our code.mil experiment. For those of you who are government and/or DoD employees, we'd like to host a Google Hangout call today at 3pm ET. Please send your government email to code@dds.mil mentioning your GitHub username & we'll send an invite to that address. We also plan to have a discussion open to the public in the future. I'll post details in a future post. 

Any non-governmental email address that comes in will be added to the list for  public discussion.

**Comment by storrgie** [comment]
Give a 72 hour warning, not 6. Push to Wednesday or Thursday so people can actually notice this.

**Comment by BrandonBouier** [comment]
@storrgie our availability is best for this afternoon. We will look at doing another one next week.

**Comment by storrgie** [comment]
See my above edit and particularly understand my point about how other organizations are chartered to do _real research_, not just run projects about _openness_. If this is your primary objective, then _make time_.

**Comment by enckse** [comment]
This is way too short of notice to properly schedule any meeting (having some work to be done and other requirements I'm supposed to be fulfilling) and, again to being open, this is now an internal "closed doors" meeting...

**Comment by fulldecent** [comment]
Time has passed. Recommending to close this issue.
