### ISSUE TITLE
FAQ gives misimpression that the public policy of Section 105 was written before the invention of software

### ISSUE THREAD

**Issue by marctjones** [deptofdefense/code.mil#69]
The FAQ says: "The legal framework that makes works created by U.S. Federal government employees ineligible for copyright protections (17 U.S.C. 105) was written long before the invention of software.". That isn't true. Section 105 was written and more importantly adopted into law several decades after the invention of software.

Section 105 was first adopted in 1976 along with the rest of the 1976 Copyright act. The [HR report on section 105](https://www.law.cornell.edu/uscode/text/17/105?qt-us_code_temp_noupdates=1#qt-us_code_temp_noupdates) states that Section 105 of the 1976 Act is similar to Section 108 of the former title of the US Code governing copyright. The 1976 Act was a significant overall and recodification of the statutory and case law governing copyright in the United States. Software/source code has existed at least since 1952 when Grace Hopper created [the first compiler.](https://en.wikipedia.org/wiki/Grace_Hopper#UNIVAC)

Further, in part because of doubts about to the extent that copyright protected software (many believed that copyright could not protect object code), the Copyright Office established the [CONTU](https://en.wikipedia.org/wiki/Software_copyright#History_of_Software_Copyrights_in_the_United_States) commission. The copyright act was amended in 1980 to make clear the role of copyright in protecting software. The purpose of the CONTU commission was to make adjusts to the copyright act to account for new technology. Interestingly it appears that the [CONTU commision](https://en.wikipedia.org/wiki/CONTU) was established in 1974 two years before the adoption of the 1976 act. Although the report was not finished until 1978 making the 1980 amendments necessary to implement the Commission's recommendations.

**Comment by shawoods** [comment]
@marctjones Maybe I was being too brief with words when writing "legal framework...was written long before..." but the legal framework does predate software. The original concept of Federal government employees not having copyright for certain materials (not all) was first codified with the Printing Law of 1895. Section 105 (first passed in 1976) is based on section 108 from the U.S. Copyright Act of 1909, so the legal framework (1895, the intervening caselaw, and 1909) does predate the existence of software. I can certainly update the FAQ if the impression is that I'm only referring to the U.S. Copyright Act of 1976.

**Comment by marctjones** [comment]
I was under the impression you were referring to the drafting of Section 105 in the 1976 Act, not merely the historical origins of copyright. But it also seems pretty clear to me that the 1976 clearly was a massive overhaul of copyright and included a consideration of software. It seems misleading to suggest that Section 105 policy does not include a consideration of software. At the time there was a great debate about if software should be copyrightable. And it was decided that everyone except the federal government has the opportunity to receive copyright protection in software. To the extent that any law can be said to have considered a policy impact, it seems like the 1976 Act as amended does consider the impact of public policy on software copyrights.

I think, in sympathy with your position, it is important to acknowledge the CONTU report and Section 105 both predate FOSS. Grant not by much, but revolutions come suddenly. FOSS is a sea change in how society thinks about intellectual "property." And certainly a lot has changed since RMS decided in 1980 that we all have the right to fix [bugs in printer drivers. ](https://en.wikipedia.org/wiki/Richard_Stallman#Events_leading_to_GNU) That sentiment I agree with. It would be great to see more government works being made accessible to the public in a way that keeps them free instead of letting a private company capture the effort and then turn around and charge for the work we paid for.

After reading the section of the house report concerning Section 105, I am leaning towards thinking that the flexibility already exists to protect the openness of the code. I am always a little sadden to see a posting in the FedReg announcing an agency competition to build an app where the rules require that all code be "open source" and yet exclude copyleft licenses. It's great that a college kid can get recognition by winning that competition. But it saddens me that that kid will have no chance of getting the government contract to enhance it or promote it. On the other hand a private company that knows how to work the procurement laws will sadly have the chance take that app and charge the government money to make it a proprietary app. It would be great for the government to ask all contractors to grant them a FOSS license, but especially in the cases where the government is asking for free work should include welcoming copyleft code too. It seems like Section 105 already gives an agency the ability to make that choice though. At the same time the policy seems pretty clear that pure government works are not entitled to copyright protection.

I would also suggest that maps are actually a really good analogy to software. Software and maps are both functional. It is also common in the map making industry to borrow information from each other. And I think that does benefit the public since maps are cheaper and more complete because mapmakers can build on each other. I think that is also true of software.

**Comment by BrandonBouier** [comment]
We've pivoted based on user feedback. Take a look at the current CONTRIBUTING.md

**Comment by marctjones** [comment]
I think we can close this issue, considering the change to the FAQ.
