### ISSUE TITLE
What is this project?

### ISSUE THREAD

**Issue by storrgie** [deptofdefense/code.mil#7]
I'm confused about what this project is (after reading through things).

Edit: sorry that seems snarky, I'm actually quite interested (we're working on similar measures at our organization) but find a lot of this to be placeholder without a clearly communicated general intent. Like, a bullet-ed list of what the intended goal is.

**Comment by BrandonBouier** [comment]
Hi @storrgie,

Code.mil is an experiment in open source at DoD. It's rolling out in phases. The first phase is the release of our draft open source agreement for comment. The next phase will occur In a few weeks, when we will finalize the agreement and then open source a few projects developed by the Defense Digital Service. We are hope you will consider providing feedback on our draft agreement and collaborate on our projects!
