### ISSUE TITLE
Is a shrinkwrap contract an additional term prohibited by the GPL

### ISSUE THREAD

**Issue by marctjones** [deptofdefense/code.mil#70]
Since your concept is to require anyone "using" the source code to agree to the contract (and submit to jurisdiction/venue of the United States, have you considered if this is an additional restriction prohibited under the terms of the GPL. 

If it is, then you will not be able to use the GPL for any of the projects adopting this approach.

**Comment by BrandonBouier** [comment]
@marctjones we have considered this, & have reached out to FSF regarding the possibility of applying GPL licenses to government works.

**Comment by BrandonBouier** [comment]
We've pivoted based on user feedback. Take a look at the current CONTRIBUTING.md

**Comment by fulldecent** [comment]
This updated project includes only the CONTRIBUTING file and allows individual agencies to choose their own license. As such, any consideration of compatibility of those licenses with GPL is now out of scope for this project. Therefore I recommend to close this issue.

**Comment by tomberek** [comment]
I would like to encourage a discussion about GPL for government works. The full consequence of a project adopting a GPL license for contributions still needs some thought and exploration.

**Comment by marctjones** [comment]
@tomberek I think you are right it is worth thinking about if the new approach is compatible with the use of the GPL, but the specific issue I was calling out here does not appear to exist with the new approach. In the interest of keeping issues focused I am closing this issue.
