### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by alabrady** [deptofdefense/code.mil#77]
I recommend adding paragraph numbers to the draft open source agreement so that specific line items can be more precisely identified between others.

**Comment by BrandonBouier** [comment]
@alabrady Thanks for the comment!

Would you be able submit a pull request that shows how you think it should look? We would appreciate it.

**Comment by shawoods** [comment]
@alabrady If you are referring to CONTRIBUTING.md, I just added numbers to the section. If you're recommending numbering beyond the first level sections, please submit a pull request.  Thanks!

**Comment by shawoods** [comment]
Section numbers and versioning added to CONTRIBUTING.md.
