### ISSUE TITLE
referencing paragraph "c" from within paragraph "c" 

### ISSUE THREAD

**Issue by alabrady** [deptofdefense/code.mil#78]
In your draft open source agreement, paragraph c basically says that others have validated the above paragraphs a & b, which is fine.. but it also says paragraph "c" which means those others have verified that they have verified.  So I think that the reference to paragraph c was probably a hold over from an earlier version of this agreement where perhaps its text was in an earlier paragraph "d."

**Comment by marctjones** [comment]
I believe you are referring to paragraph c of the text of the DCO. The DCO is a well known certificate used by the Linux kernel project. The circular reference to paragraph c refers to situations were multiple people have passed on a patch up through multiple levels of maintainers.

Changing any of the text of the DCO would only serve to cause confusion as people will generally expect it to be the exact same text as the DCO used by the Linux group. Not to mention the fact that the copyright license on the DCO does not permit modifications. 

I would recommend closing this issue. If the DCO has issues, one could argue for a different process, but it shouldn't be modified.

**Comment by tomberek** [comment]
Concur with @marctjones. Closing.
