### ISSUE TITLE
Some questions on forking projects licensed per the Proposal

### ISSUE THREAD

**Issue by dosaygo-coder-0** [deptofdefense/code.mil#83]
Maybe this is not important to consider right now, but in case it's on topic, here are some questions I have if I wanted to fork or otherwise adapt software that came from a project with the proposed CONTRIBUTING.md file

- If I forked it to a project "located in" ( whatever that means ) another country that did have copyright protections, could I just omit the CONTRIBUTING.md and keep whatever LICENSE was filled with?
- If I forked it to a project in the U.S, do I need to keep the CONTRIBUTING.md file?

**Comment by fulldecent** [comment]
Software is international. And remember the US government has plenty of people that work abroad and are subject to the laws of other countries. So this project is definitely applicable to a global audience.

You are free to fork and do whatever you want with the code, restricted by any requirements in the licenses of the project.

In all licenses that we are considering there has been no discussion of requiring you to keep CONTRIBUTING.md.

**Comment by ckaran** [comment]
As I understand it from Army Research Laboratory lawyers, copyright is something that is attached at the moment of creation; it cannot be added to material afterwards.  That means that works that were in the public domain at the time of their creation and in the place where they were located are still in the public domain, even when forked to a different jurisdiction.  Note that I am not a lawyer, and this is not legal advice.

**Comment by marctjones** [comment]
@ckaran  I think you have that right. 

For better or worse copyrights are legally a property right granted by statute within a specific jurisdiction. There is some theoretical debate about if intellectual property and copyrights should be considered "natural rights" but historically and in practice they have always been considered creatures of statute so exist as a result of the favor of the state.  

In most countries, the United States and I think all Western European countries, copyright attaches the moment you create the work. There are exceptions the most relevant one here being that the U.S. government denies itself the right to copyright protection. So it's not as if the US government gave up its copyrights, those rights never existed in the United States. The statutory title that grants everyone else copyrights (including foreign governments) specifically says the U.S. government is not entitled to them. (I think I got that right @shawoods? ). But at the moment the U.S. government authors a work here, the Canadian government is also making a policy decision about if a copyright is granted in that work to the U.S. government in Canada. 

So at the moment you fix your expression of an idea in some medium every country in the world is either granting or not granting you a copyright within their jurisdiction to that expression. The rights exist (or don't exist) simultaneously in every jurisdiction. The existence of copyright does not matter where you are (not technically true, a whole mess of rules about where publication takes place and its effect.) Where you take actions that exercise or rather violate someone's copyrights is in practice what matters.

**Comment by ckaran** [comment]
@marctjones  I feel like we're now dealing with [Schrodinger's cat](https://en.wikipedia.org/wiki/Schr%C3%B6dinger's_cat)!

**Comment by marctjones** [comment]
It is hard to make a universally true statement. But I do like [cats!](http://xin-rou.blogspot.com/2012/06/kitten-may-you-rest-in-peace.html)

**Comment by ckaran** [comment]
@marctjones :(

**Comment by shawoods** [comment]
@dosaygo-coder-0 The CONTRIBUTING.md file never has to be included in a fork.  Whether LICENSE.md has to be included in a fork depends on the status of the project at the time. 

*If there have been no merged copyrighted contributions, and you're in a jurisdiction where the Government written code is not eligible for copyright protections (e.g., the U.S.), then you do not need to keep LICENSE.md. It might be helpful to have some explanation similar to section 1 in CONTRIBUTING.md in the README to explain the copyright status, but it's not strictly necessary. 
*If there are merged copyrighted contributions, or you're in a jurisdiction where the Government written code is eligible for copyright protections, then you would need to keep LICENSE.md in the fork (assuming you've forked the entire project inclusive of the copyrighted code) and abide by the terms of the license.  

We will update the FAQ with this information.

With a forked project where at least some of the code is subject to LICENSE.md, the fork originator could theoretically merge his/her own code, and then license that original code under LICENSE.md or another compatible license.

**Comment by dosaygo-coder-0** [comment]
@shawoods okay I got it. That's clear after I read it a few times.

@marctjones thanks for contributing that explanation about copyright across jurisdictions. I ( probably unjustifiably ) feel like an expert after reading it.

**Comment by shawoods** [comment]
Closing because @dosaygo-coder-0 said his question was answered.
