### ISSUE TITLE
CC0 public dedication probably better

### ISSUE THREAD

**Issue by sgnn7** [deptofdefense/code.mil#86]
Technically, code here can probably fall under CC0 copyright/ownership waiver for public work and you can use that legal text instead of making your own:
- https://creativecommons.org/publicdomain/zero/1.0/legalcode
- https://wiki.creativecommons.org/wiki/CC0

**Comment by sgnn7** [comment]
Closing since I just found the FAQs that cover this

**Comment by sgnn7** [comment]
Sidenote: it might be good to add the FAQ link to the main docuent

**Comment by tomberek** [comment]
@sgnn7 Adding link to FAQ in #90
