### ISSUE TITLE
Contact the folks at Code.gov

### ISSUE THREAD

**Issue by ckaran** [deptofdefense/code.mil#9]
If you haven't already done so, please contact the folks at [code.gov](https://code.gov).  They can offer good guidance on what to do.

**Comment by tomberek** [comment]
We are in touch with them and collaborating. Thanks!

**Comment by ckaran** [comment]
@tomberek Does anyone from code.mil attend the meetings in DC?  I'd like to meet you guys in person at the next meeting if possible.
