### ISSUE TITLE
从历史来看这是非常重要的

### ISSUE THREAD

**Issue by wuethan** [deptofdefense/code.mil#94]
这意味着让更多的开发者了解到何种水平才能步入这个领域，如何才能做好安全，从历史来看这也是一次重要的开源，希望包括我在内的开发者能享受这份喜悦

**Comment by testsecer** [comment]
美国防部厉害了！！！！！

**Comment by fulldecent** [comment]
那是的！

**Comment by shawoods** [comment]
Thanks for the support.
