### ISSUE TITLE
Liability of contributors under current Developer Certificate of Origin Version 1.1

### ISSUE THREAD

**Issue by VhatAmI** [deptofdefense/code.mil#96]
In most open source there is something stating software is provided AS-IS 
etc. to deflect liability from present or future bugs that might occur in a prospective authors code. 

Will the DOD be holding code authors liable for bugs or issues? 
Will there be some protections put into place? 

The way I see it a good faith commit (not one that is intentionally malicious) would be reviewed by the DOD before a pull request and then once the pull request is accepted the liability of the author would be negligible. 

Am I correct in the above assumption? Or is the DOD looking at this in a different light? 
Thank you for your time.

**Comment by richardfontana** [comment]
Under the DCO a contribution is submitted under the applicable open source license of the project which  (I'm sure in all cases the DoD is contemplating) will have warranty/liability disclaimers.

**Comment by shawoods** [comment]
I think this issue has been answered per @richardfontana. Please see https://github.com/deptofdefense/code.mil/blob/master/FAQ.md#what-is-the-liability-of-a-contributor in the FAQ update. If anyone has anymore questions/concerns on this point we can always reopen.
